export enum Specialty {
    CARDIOLOGIST = "CARDIOLOGIST",            
    DERMATOLOGIST = "DERMATOLOGIST",          
    NEUROLOGIST = "NEUROLOGIST",              
    PEDIATRICIAN = "PEDIATRICIAN",            
    GASTROENTEROLOGIST = "GASTROENTEROLOGIST",
    PSYCHIATRIST = "PSYCHIATRIST",            
    RHEUMATOLOGIST = "RHEUMATOLOGIST"         
}